### PR TITLE
Add Django 5.1+ support for `CheckConstraint condition` with backward compatibility

### PR DESCRIPTION
**Pull request by saJaeHyukc**
This PR adds support for `CheckConstraint.condition` in Django 5.1 while maintaining backward compatibility with Django 4.2 by dynamically selecting between condition and check based on the Django version.

### CODE REVIEW

**Comment by saJaeHyukc** [comment]
@RealOrangeOne The current issue with mypy is that it indicates that condition is not defined. Should this be adjusted to match the version of django-stubs?

Here is the relevant line in django-stubs:
https://github.com/typeddjango/django-stubs/blob/df12deb6b30623c0661b920a4eece8135306b55d/django-stubs/db/models/constraints.pyi#L48C1-L67C19

**Comment by RealOrangeOne** [comment]
If there's an overload, I'm surprised this is failing. If dependencies need updating, feel free to do so. Alternatively, I'm ok adding a type ignore for these lines.

**Comment by saJaeHyukc** [comment]
> If there's an overload, I'm surprised this is failing. If dependencies need updating, feel free to do so. Alternatively, I'm ok adding a type ignore for these lines.

I've added a type ignore for these lines as suggested. :)

**Comment by silviogutierrez** [comment]
I believe the migration also needs this check (0005 at least) or you'll continue getting the deprecation warning during tests and the like.

**Comment by dchimeno** [comment]
and given this, it's gonna fail with django 6

```bash
  File "/usr/local/lib/python3.12/site-packages/django_tasks/backends/database/migrations/0005_alter_dbtaskresult_priority_and_more.py", line 6, in <module>
    class Migration(migrations.Migration):
  File "/usr/local/lib/python3.12/site-packages/django_tasks/backends/database/migrations/0005_alter_dbtaskresult_priority_and_more.py", line 19, in Migration
    constraint=models.CheckConstraint(
               ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CheckConstraint.__init__() got an unexpected keyword argument 'check'
make: *** [Makefile:23: test] Error 1
```

**Pull request merged**
